### ISSUE TITLE
Error loading rules - createDatabase

### ISSUE THREAD

**Issue by prashantkurlekar** [agrinman/sift-ios#1]
Throws error at launch. Error loading rules - createDatabase
![img_739141fa42f2-1](https://user-images.githubusercontent.com/4653712/41196606-8a5f9174-6c87-11e8-9bd5-57302c4eca19.jpeg)

**Comment by agrinman** [comment]
Did you change the bundle id in project settings? In `Constants.swift:12`, change  `appGroupIdentifier` to the matching shared app group. I'll add this to the readme thanks.
