### ISSUE TITLE
Better deployment guide

### ISSUE THREAD

**Issue by kaunteya** [agrinman/sift-ios#7]
README should have a detailed deployment guide, which includes changing of id in `General` and `Capabilities` section and also integrating `AwesomeCache` so that issues like #4 and #6 are not raised.

**Comment by llabball** [comment]
I've taken screenshots during the configuration. Should i send a PR to the README or is someone else already writing a guide?

**Comment by agrinman** [comment]
@llabball I'm planning to release a guide -- but in the mean-time would definitely appreciate a PR to the README with screen shots!
